// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nncfvsjppvsodpqtcopc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uY2Z2c2pwcHZzb2RwcXRjb3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzE5OTEsImV4cCI6MjA3NDM0Nzk5MX0.RLKGrp7zLvt_9DAHhkW5WT9TnAmI_QP7Bhe9Np83rFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});